name: "Check"

on:
  pull_request:
    branches:
      - main

jobs:
  configuration:
    name: "Configuration"
    runs-on: "ubuntu-latest"

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Compile TypeScript sources
        uses: ./.github/actions/build

      - name: Run checks
        run: npm run check

      - name: Write PR number
        run: echo "${{ github.event.number }}" >> ./config/pr.yaml

      - name: Upload configuration as artifact
        uses: actions/upload-artifact@v4
        with:
          name: groups.yaml
          path: ./config/*.yaml
